"""
Demo: Operator Overloading — Dunder Arithmetic & Rich Comparisons
Run:  python demo.py
"""
import math
from functools import total_ordering

# ── Section 1: __add__ / __radd__ fallback chain ────────────────────────────
print("=" * 50)
print("Section 1: __add__ / __radd__ chain")
print("=" * 50)

class Money:
    def __init__(self, amount, currency="USD"):
        self.amount   = amount
        self.currency = currency

    def __add__(self, other):
        if isinstance(other, Money):
            if self.currency != other.currency:
                return NotImplemented   # signal: try other.__radd__
            return Money(self.amount + other.amount, self.currency)
        return NotImplemented

    def __radd__(self, other):
        if other == 0:            # sum() compatibility
            return self
        return NotImplemented

    def __repr__(self):
        return f"Money({self.amount} {self.currency})"

usd5  = Money(5, "USD")
usd10 = Money(10, "USD")
eur3  = Money(3, "EUR")

print(usd5 + usd10)             # Money(15 USD)
print(sum([usd5, usd10]))       # Money(15 USD) — radd(0) used

try:
    result = usd5 + eur3
    print(result)
except TypeError as e:
    print("Mixed currency:", e)

# ── Section 2: __iadd__ must return self ────────────────────────────────────
print("\n" + "=" * 50)
print("Section 2: __iadd__ trap")
print("=" * 50)

class BadVec:
    def __init__(self, x):
        self.x = x
    def __iadd__(self, other):
        self.x += other.x
        # BUG: missing return self

class GoodVec:
    def __init__(self, x):
        self.x = x
    def __iadd__(self, other):
        self.x += other.x
        return self             # MUST return self

b = BadVec(1)
b += BadVec(2)
print("BadVec after +=:", b)    # None — rebind happened, lost the object!

g = GoodVec(1)
g += GoodVec(2)
print("GoodVec after +=:", g.x) # 3

# ── Section 3: __eq__ kills __hash__ ────────────────────────────────────────
print("\n" + "=" * 50)
print("Section 3: __eq__ + __hash__ contract")
print("=" * 50)

class NoHash:
    def __eq__(self, other):
        return True

try:
    d = {NoHash(): "oops"}
except TypeError as e:
    print("Unhashable:", e)

class WithHash:
    def __eq__(self, other):
        return True
    def __hash__(self):
        return 42

d = {WithHash(): "ok"}
print("Hashable dict:", d)

# ── Section 4: total_ordering ────────────────────────────────────────────────
print("\n" + "=" * 50)
print("Section 4: total_ordering")
print("=" * 50)

@total_ordering
class Version:
    def __init__(self, major, minor):
        self.t = (major, minor)
    def __eq__(self, other):
        return self.t == other.t
    def __lt__(self, other):
        return self.t < other.t
    def __repr__(self):
        return f"Version{self.t}"

v1 = Version(1, 2)
v2 = Version(1, 9)
v3 = Version(2, 0)
print(sorted([v3, v1, v2]))    # needs __lt__: should print ordered
print(v1 <= v2, v3 > v2)       # generated by total_ordering

if __name__ == "__main__":
    print("\nAll sections complete.")
